version: "3.9"

services: 
  database:
    image: mysql
    container_name: cryptum-db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=cryptum_backend
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysqlq_data:/var/lib/mysql

  app:
    build: .
    container_name: cryptum
    restart: always
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  mysqlq_data: